"""datamodels v0.7

Revision ID: 14ebcbdf6337
Revises: 86717eb8ebd7
Create Date: 2025-04-01 14:14:33.238986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ebcbdf6337'
down_revision: Union[str, None] = '86717eb8ebd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_network', sa.Column('ip_address', sa.String(length=32), nullable=False))
    op.drop_column('location_network', 'ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_network', sa.Column('ip', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('location_network', 'ip_address')
    # ### end Alembic commands ###
