"""datamodels v0.9

Revision ID: 64a676369888
Revises: c00d6d7d197c
Create Date: 2025-05-08 14:38:53.326918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a676369888'
down_revision: Union[str, None] = 'c00d6d7d197c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_process', sa.Column('device_credibily', sa.Float(), nullable=True))
    op.add_column('auth_process', sa.Column('net_loc_credibility', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_process', 'net_loc_credibility')
    op.drop_column('auth_process', 'device_credibily')
    # ### end Alembic commands ###
