"""datamodels_v0.6

Revision ID: 86717eb8ebd7
Revises: bcca17723bff
Create Date: 2025-04-01 13:38:33.753246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86717eb8ebd7'
down_revision: Union[str, None] = 'bcca17723bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_process', sa.Column('risk_eval_vars', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_process', 'risk_eval_vars')
    # ### end Alembic commands ###
