"""datamodel v0.3

Revision ID: b0e1146d79df
Revises: d4ae2df3f484
Create Date: 2025-03-25 15:09:35.437894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e1146d79df'
down_revision: Union[str, None] = 'd4ae2df3f484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_event_auth_context_hash_fkey', 'auth_event', type_='foreignkey')
    op.drop_constraint('auth_process_auth_context_hash_fkey', 'auth_process', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('auth_process_auth_context_hash_fkey', 'auth_process', 'auth_context', ['auth_context_hash'], ['hash'])
    op.create_foreign_key('auth_event_auth_context_hash_fkey', 'auth_event', 'auth_context', ['auth_context_hash'], ['hash'])
    # ### end Alembic commands ###
