"""data_models_v0.5

Revision ID: bcca17723bff
Revises: be7df28d6728
Create Date: 2025-03-25 15:55:29.177958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcca17723bff'
down_revision: Union[str, None] = 'be7df28d6728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location_network', 'country',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location_network', 'country',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
