"""datamodel v0.4

Revision ID: be7df28d6728
Revises: b0e1146d79df
Create Date: 2025-03-25 15:40:06.128852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7df28d6728'
down_revision: Union[str, None] = 'b0e1146d79df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('client', sa.String(length=128), nullable=True))
    op.drop_column('device', 'info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('info', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('device', 'client')
    # ### end Alembic commands ###
