"""data_models_v0.2

Revision ID: d4ae2df3f484
Revises: ed5c12c1043a
Create Date: 2025-03-21 15:11:53.335176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ae2df3f484'
down_revision: Union[str, None] = 'ed5c12c1043a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_event', sa.Column('auth_context_hash', sa.String(length=64), nullable=True))
    op.add_column('auth_event', sa.Column('device_info_hash', sa.String(length=64), nullable=True))
    op.add_column('auth_event', sa.Column('network_location_hash', sa.String(length=64), nullable=True))
    op.alter_column('auth_event', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'auth_event', 'device', ['device_info_hash'], ['hash'])
    op.create_foreign_key(None, 'auth_event', 'location_network', ['network_location_hash'], ['hash'])
    op.create_foreign_key(None, 'auth_event', 'auth_context', ['auth_context_hash'], ['hash'])
    op.alter_column('auth_process', 'auth_context_hash',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('auth_process', 'device_info_hash',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('auth_process', 'network_location_hash',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False)
    op.add_column('device', sa.Column('device', sa.String(length=64), nullable=False))
    op.drop_column('device', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('client', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('device', 'device')
    op.alter_column('auth_process', 'network_location_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('auth_process', 'device_info_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('auth_process', 'auth_context_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_constraint(None, 'auth_event', type_='foreignkey')
    op.drop_constraint(None, 'auth_event', type_='foreignkey')
    op.drop_constraint(None, 'auth_event', type_='foreignkey')
    op.alter_column('auth_event', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('auth_event', 'network_location_hash')
    op.drop_column('auth_event', 'device_info_hash')
    op.drop_column('auth_event', 'auth_context_hash')
    # ### end Alembic commands ###
