"""
# DecisionRequest Pydantic Schema

The **DecisionRequest** Pydantic schema is used to validate incoming request
data for authentication risk level evaluation. This ensures that the required fields
are present and correctly formatted.
"""

from pydantic import BaseModel, Field, field_validator

from src.utils.validation.ip_address_type import validate_ip_input
from src.utils.validation.regex import SCREEN_RESOLUTION_REGEX


class DecisionRequest(BaseModel):
    """
    ## Fields

    - **event_id (UUID)**:
      Identifier of this authentication process generated by the Keycloak SPI.
    - **group_id (str)**:
      Identifier for a group within a realm for parameters config.
    - **realm_id (str)**:
      Identifier for the realm in which the request is made.
    - **user_id (UUID)**:
      UUID formatted string identifying the user making the request.
    - **client (str)**:
      Name or identifier of the client application making the request.
    - **ip_address (str)**:
      IP address of the user initiating the request.
    - **user_agent (str)**:
      String representation of the user agent (typically includes browser and OS info).
    - **system_language (str)**:
      Language setting of the user's system or client.
    - **screen_resolution (str)**:
      Screen resolution of the user's device.
    - **cookie (str | None)**:
      Optional cookie string.
    """

    event_id: str = Field(
        ...,
        description="Identifier of this authentication process generated by the Keycloak SPI.",
    )
    group_id: str = Field(
        ...,
        description="Identifier for a group within a realm for parameters config.",
    )
    realm_id: str = Field(
        ..., description="Identifier for the realm in which the request is made."
    )
    user_id: str = Field(
        ..., description="UUID identifying the user making the request."
    )
    client: str = Field(
        ...,
        description="Name or identifier of the client application making the request.",
    )
    ip_address: str = Field(
        ..., description="IP address of the user initiating the request."
    )
    user_agent: str = Field(
        ..., description="User agent string indicating browser and OS details."
    )
    system_language: str = Field(
        ..., description="Language setting of the user's system or client."
    )
    screen_resolution: str = Field(
        ..., description="Screen resolution of the user's device."
    )
    auth_context_hash: str = Field(..., description="Auth context hash.")
    cookie: str | None = Field(None, description="Optional cookie string.")

    @field_validator("ip_address")
    def validate_ip_address(cls, v: str) -> str:
        """
        Allow plain IPv4, IPv4/CIDR, or IPv6. Raises ValueError otherwise.
        """
        try:
            validate_ip_input(v)
        except ValueError:
            raise ValueError(
                f"'{v}' is not a valid IPv4 address, IPv4 CIDR block, or IPv6 address"
            )
        return v

    @field_validator("screen_resolution")
    def validate_screen_resolution(cls, v: str) -> str:
        """
        Require the "<digits>x<digits>" form ScreenResolutionChecker expects
        (e.g. "1920x1080"). Anything else is rejected here, at the request
        boundary, rather than reaching the risk evaluation and aborting it --
        an unconstrained value let a single malformed field (or an empty
        string) suppress the entire adaptive decision.
        """
        if not SCREEN_RESOLUTION_REGEX.fullmatch(v):
            raise ValueError(
                f"'{v}' is not a valid screen resolution (expected '<width>x<height>', "
                f"e.g. '1920x1080')"
            )
        return v
